# Generated by Django 5.1.2 on 2024-10-24 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sporcu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100)),
                ('soyad', models.CharField(max_length=100)),
                ('dogum_tarihi', models.DateField()),
                ('kilo', models.DecimalField(decimal_places=2, max_digits=5)),
                ('boyUzunlugu', models.DecimalField(decimal_places=2, max_digits=5)),
                ('kacAylik', models.IntegerField()),
            ],
        ),
    ]
