# Generated by Django 5.1.2 on 2024-10-24 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spor_AI', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sporcu',
            options={'verbose_name': 'Sporcu', 'verbose_name_plural': 'Sporcular'},
        ),
    ]
