# Generated by Django 5.1.2 on 2024-10-24 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spor_AI', '0002_alter_sporcu_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='sporcu',
            name='ekstra_aciklama',
            field=models.TextField(blank=True, null=True),
        ),
    ]
