# Generated by Django 5.1.2 on 2024-10-24 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spor_AI', '0003_sporcu_ekstra_aciklama'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sporcu',
            old_name='boyUzunlugu',
            new_name='boy_uzunlugu',
        ),
        migrations.RenameField(
            model_name='sporcu',
            old_name='kacAylik',
            new_name='kac_aylik',
        ),
    ]
