# Generated by Django 5.1.2 on 2024-10-30 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spor_AI', '0005_rename_boy_uzunlugu_sporcu_boyuzunlugu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sporcu',
            name='ad',
            field=models.CharField(max_length=100, verbose_name='Ad'),
        ),
        migrations.AlterField(
            model_name='sporcu',
            name='boyUzunlugu',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Boy Uzunluğu'),
        ),
        migrations.AlterField(
            model_name='sporcu',
            name='dogum_tarihi',
            field=models.DateField(verbose_name='Doğum Tarihi'),
        ),
        migrations.AlterField(
            model_name='sporcu',
            name='ekstra_aciklama',
            field=models.TextField(blank=True, null=True, verbose_name='Eklemek istedikleriniz'),
        ),
        migrations.AlterField(
            model_name='sporcu',
            name='kacAylik',
            field=models.IntegerField(verbose_name='Kaç aylık yazılmak istiyorsunuz ?'),
        ),
        migrations.AlterField(
            model_name='sporcu',
            name='kilo',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Vücut Ağırlığı'),
        ),
        migrations.AlterField(
            model_name='sporcu',
            name='soyad',
            field=models.CharField(max_length=100, verbose_name='Soyad'),
        ),
    ]
